name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: URL Mapping Tests
      id: url-mapping-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: URL Mapping Tests
        setup-command: pip install -r requirements.txt && python manage.py migrate
        command: DJANGO_SETTINGS_MODULE=workshop_project.settings python -m pytest
          tests/test_assignment_0.py -v
        timeout: 10
        max-score: 100
    - name: Django Check
      id: django-check
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Django Check
        setup-command: ''
        command: DJANGO_SETTINGS_MODULE=workshop_project.settings python manage.py
          check
        timeout: 5
        max-score: 0
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        URL-MAPPING-TESTS_RESULTS: "${{steps.url-mapping-tests.outputs.result}}"
        DJANGO-CHECK_RESULTS: "${{steps.django-check.outputs.result}}"
      with:
        runners: url-mapping-tests,django-check
